# Generated by Django 5.1.4 on 2024-12-21 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_images/')),
                ('detection_type', models.CharField(choices=[('brain_tumor', 'Brain Tumor Detection'), ('cancer', 'Cancer Detection')], max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction_result', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('prediction_class', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medical_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.medicalimage')),
            ],
        ),
    ]
