# Generated by Django 5.1.4 on 2024-12-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_patient_remove_predictionresult_medical_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
