# Generated by Django 5.1.4 on 2024-12-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_analysis_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="note",
            new_name="notes",
        ),
    ]
