# Generated by Django 5.1.4 on 2024-12-28 11:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_disease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.CharField(
                default=api.models.generate_patient_id,
                editable=False,
                max_length=7,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
