# Generated by Django 5.1.4 on 2024-12-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_trainingimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
