# Generated by Django 5.1.4 on 2024-12-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_trainingimage_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingimage",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="trainingimage",
            name="label",
        ),
        migrations.CreateModel(
            name="TrainingClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="api.disease",
                    ),
                ),
            ],
            options={
                "unique_together": {("disease", "key")},
            },
        ),
        migrations.AddField(
            model_name="trainingimage",
            name="training_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.trainingclass",
            ),
        ),
    ]
