# Generated by Django 5.1.4 on 2025-01-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
