# Generated by Django 5.1.4 on 2025-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_patient_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="stage_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
